baseURL = "https://willamis.netlify.app/"
languageCode = "pt-br"
title = "Willamis"
theme = "PaperMod"

relativeURLs = false
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
defaultTheme = "auto"
mainSections = ["posts"]
enableSearch = true
customCSS = ["css/extended/custom.css"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Sobre"
    url = "/pages/about/"
    weight = 2

  [[menu.main]]
    name = "Pesquisar"
    url = "/search/"
    weight = 3

